### ISSUE TITLE
Update themes for PowerShell 5

### ISSUE THREAD

**Issue by balbano** [lukesampson/concfg#10]
Many of the themes behave poorly with the new syntax highlighting in powershell 5. For example, typing numbers in many of the light themes results in white on white, or close to it, and typing command line flags in many of the dark themes results in grey on grey, or close to it. The new Mountain theme seems to do okay.
### Examples

![white_on_white_numbers](https://cloud.githubusercontent.com/assets/4529191/9833031/00caadfc-594f-11e5-90ac-be49d1998eab.png)

![flags_hard_to_read](https://cloud.githubusercontent.com/assets/4529191/9833032/02b95a28-594f-11e5-9bd5-5a563f7f3b8d.png)

**Comment by lukesampson** [comment]
Yeah I think this is the new ps-readline stuff.

I've used 

```set-psreadlineoption -t parameter darkblue
set-psreadlineoption -t operator darkblue
set-psreadlineoption -t string darkgreen
```
... to get mine looking better for now. This isn't a solution, just mentioning it now until I get a chance to fix this properly.

**Comment by mrmckeb** [comment]
Thanks @lukesampson - I didn't realise it was because of the new PowerShell, as I hadn't used it prior. Makes sense.

**Comment by ionTea** [comment]
Hey, I have the same problem and i'm not used to powershell so i have no idea where to look in order to fix this. Where can i find the config file to add the above temp-fix?

**Comment by lukesampson** [comment]
@ionTea you can add the above commands to your powershell profile (e.g. `notepad $profile`) to save them.

**Comment by AdrianoCahete** [comment]
Still have a problem when start character is ```$```:
![colors](https://cloud.githubusercontent.com/assets/37474/13465225/713b9500-e073-11e5-986d-8f201cf0e2ab.PNG)

Any fix?

**Comment by nwykes** [comment]
@AdrianoCahete if you're still have a problem with the $ it can be set with:
```set-psreadlineoption -t variable darkblue```

**Comment by stanleystl** [comment]
If you are using the solarized theme, I fixed some hard to read colors and also replaced others to make them better (in my opinion). I created the PR #20 for those who'd like to try it and maybe to be merged to this repo.

**Comment by h404bi** [comment]
https://github.com/h404bi/base16-concfg#about-command-line-token-colors
When I regenerate the presets with the [base16](https://github.com/chriskempson/base16) architecture, I met this problem while using those generated presets, then I found the reason, and gave a explanation. I think that's the finial solution.
