### ISSUE TITLE
Prompts during import

### ISSUE THREAD

**Issue by dennislloydjr** [lukesampson/concfg#2]
Hi Luke,

This is a very cool script. I'd like to incorporate it in my automated dev box script. When I run:

```
concfg import solarized
```

It prompts to clean overrides in the registry. Can a way be added so that it does not prompt for this so that scripts can complete without user interaction?

Thanks,
Dennis

**Comment by roysubs** [comment]
I'm trying to get concfg working and I can't import anything much. Any tips on this sir?
![image](https://user-images.githubusercontent.com/16388699/201536314-5bf4009b-609b-4993-93c1-bb4e35ba82cd.png)
