### ISSUE TITLE
Importing new sample needs switch back and forth from legacy mode

### ISSUE THREAD

**Issue by andreatulimiero** [lukesampson/concfg#21]
I'm using Windows 10, my build is 14391, and whenever I'm importing a new schema I need to switch legacy console and then back to normal to have the theme applied <br/>
Don't know why but it's working only this way

**Comment by h404bi** [comment]
I'll close this since concfg has changed a lot. Please try the latest version if you are still using concfg. And you can open a new issue if you are still encountering the problem.
