### ISSUE TITLE
Reset default powershell colors

### ISSUE THREAD

**Issue by Rudde** [lukesampson/concfg#25]
Hello.

concfg affected more terminals on my system then I would like and I wanted to reset my colors to defaults. I ran `concfg import defaults` as per documentation to get stock colors, however this does not give me standard colors, it turns the blue powershell into a black cmd looking thing.

**Comment by lukesampson** [comment]
Try `concfg import powershell-defaults` for the powershell default theme.

**Comment by Rudde** [comment]
Yeah, that's powershell, but that will also make cmd blue and "windows subsystem for linux"-bash blue.

**Comment by lukesampson** [comment]
I agree it would be good to affect only the current shell.

Console appearance settings can be stored in the registry under HKCU\Console and overridden by `HKCU\Console\Path_To_Shell.exe` or in the properties of the shortcut (.lnk) that was used to open the shell.

I have included defaults for the registry and the default Powershell shortcuts under `%APPDATA%\Microsoft\Windows\Start Menu\Programs\Windows Powershell` if that helps to restore your defaults.
[defaults.zip](https://github.com/lukesampson/concfg/files/598689/defaults.zip)

**Comment by Rudde** [comment]
Hey thanks man. If I open Powershell from system32 it is as it's supposed to, but I'm not sure what those lnk files are, these does not seem like windows-shortscuts at all.

**Comment by lukesampson** [comment]
The .lnk files are from Windows 10 – maybe if you're on an earlier version of Windows they won't work?

The way I got the default shortcuts was to create a new user account and log into it. The default powershell shortcuts should be generated under `%APPDATA%\Microsoft\Windows\Start Menu\Programs\Windows Powershell`.

**Comment by Rudde** [comment]
If you open `Windows PowerShell.lnk` in notepad you see it seems like it's something for parallels windows 10 virtual machine or something.

**Comment by lukesampson** [comment]
Yikes, sorry about that. Does this one work?
[powershell_shortcuts.zip](https://github.com/lukesampson/concfg/files/599780/powershell_shortcuts.zip)

**Comment by Rudde** [comment]
Hello, thanks! That seems to have restored everything back to normal. 

I would still like to change the PowerShell look with concfg, I just don't like that it affect especially bash. Would there be a way I can target the .lnk files to only change the look and feel of powershell with concfg and keep everything else untouched?

**Comment by lukesampson** [comment]
It would be possible to change just powershell. Changing console properties on a .lnk is difficult to do programmatically, but updating the HKCU\Console subkeys in the registry (rather than HKCU\Console itself) should work, after removing the custom properties from the .lnk. Might also need to work out which parent shell is currently running, or come up with an interface for the user to specify which shell to change, since some people (myself included) prefer all consoles to look the same.

I probably won't have time or motivation to tackle this any time soon, but I'd be happy to accept a pull request if you can work it out.
