### ISSUE TITLE
Colors are wrong

### ISSUE THREAD

**Issue by andreatulimiero** [lukesampson/concfg#27]
I'm using concfg to customize the theme of my Powershell but it's working.
This are the commands I've launched:
`concfg import solarized small` (then answered yes to all)
This is the result
<img width="574" alt="powershell" src="https://cloud.githubusercontent.com/assets/7541987/23102391/75ee5802-f6a8-11e6-9451-5015720820fa.PNG">

My Win Build is **10.0.14931**

**Comment by lukesampson** [comment]
Have you tried running `concfg clean` manually? If you answered Y to everything it should have done this for you, but it might be worth another try.

Do you see any errors when you were importing? If you have overridden default PowerShell aliases like `sp` and `ni` then that might be causing the script not to work.

Another thing to check might be your PSReadLine options (e.g. `Get-PSReadLineOption`) if you have configured those.

You are running a more recent build than what I have (14393) so maybe Microsoft have updated the way things work.

Console colors can be stored in the registry and in the shortcut files that you use to start PowerShell, and these can override the colors you import with `concfg import`.

`concfg clean` removes the overrides from known locations, but maybe there are new registry settings (or new shortcuts) that are affecting this. You can see more detail about which locations are checked in the [clean](https://github.com/lukesampson/concfg/blob/master/libexec/clean.ps1) script. If you have any subkeys of `hkcu:\Console` in the registry, these are probably the culprits.

**Comment by andreatulimiero** [comment]
I kind of fix it copying the colors values from the default panel to the properties panel of the powershell
<img width="284" alt="defaults" src="https://cloud.githubusercontent.com/assets/7541987/23668216/b2f7be22-0360-11e7-8fa6-9ff19282ce8a.PNG">
I don't know why this happens, but is looking almost good now
However, it's a pity I can only change 4 of the colors, since from the panel you can only set those 4
<img width="796" alt="screen" src="https://cloud.githubusercontent.com/assets/7541987/23668215/b2f69858-0360-11e7-9390-d8ca61c5e0ff.PNG">
