### ISSUE TITLE
concfg import solarized fails

### ISSUE THREAD

**Issue by jcollum-cambia** [lukesampson/concfg#31]
```
$ concfg import solarized
fatal: Not a git repository (or any of the parent directories): .git
concfg: ERROR: couldn't load settings from solarized

$ pwd

Path
----
C:\Users\xxxxxxx

```
Is there a `verbose` mode I can put it into when installing? 

Tried the help and got similar failures: 

```
$ concfg --help
usage: concfg <command> [<args]

Some useful commands are:
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git

clean
export
help
import
presets


type 'concfg help <command>' to get help for a specific command
$
```

I bet this is related to our proxy. Ugh.

**Comment by lukesampson** [comment]
You can use `set-psdebug -trace 2` to show the PowerShell calls being made. It's very verbose, so it might require some digging to track the error down. Use `set-psdebug -off` to turn debugging off again.

As concfg shouldn't be calling git, it looks like there might be a command conflict with `gc` or another PowerShell command/alias having being re-assigned on your system.

**Comment by jcollum-cambia** [comment]
Yeah that was it. I alias gc to "git commit". But uhhh 

>Powershell Best Practice #1: Use full cmdlet name (not alias)

http://powershell-guru.com/powershell-best-practice-1-use-full-cmdlet-name-not-alias/
