### ISSUE TITLE
files in directory listing are illegible with most themes

### ISSUE THREAD

**Issue by jderose9** [lukesampson/concfg#32]
Most themes I have tried (monokai, tomorrow, oceannext, mocha) have basically illegible file listings from dir/ls as any files which are not text files or executables are presented with a very dark gray color. Any ideas on how this can be resolved? Thanks!

![image](https://user-images.githubusercontent.com/2118702/28089483-21aa009c-6657-11e7-9b9e-b147f9fe9831.png)

**Comment by lukesampson** [comment]
Assuming this screenshot is from a PowerShell session, are you using [PSColor](https://github.com/Davlind/PSColor) or some other override for PowerShell's `Get-ChildItem`? The default `dir`/`ls`/`Get-ChildItem` output for PowerShell 5.1 doesn't seem to use different colors.

**Comment by jderose9** [comment]
Ahh I didn't realize that. I found this is caused by the pshazz xpando theme.

https://github.com/lukesampson/pshazz/blob/master/themes/xpando.json

`[".*",                                                "darkgray",   ""]`

**Comment by lukesampson** [comment]
Ah, of course! Nice find. You're very welcome.
