### ISSUE TITLE
Turns my human console into a tiny console for ants

### ISSUE THREAD

**Issue by riverar** [lukesampson/concfg#33]
Regardless of what I import, I get this squished tiny atrocity that I haven't figured out how to resolve. 

Does this software work anymore?

![image](https://user-images.githubusercontent.com/475132/30223233-d0343e98-947e-11e7-9fdc-1bd6bd8b5ec6.png)

Windows 10 build 16353
Normal DPI scaling
1920x1200 desktop
Mouse present

**Comment by sheldonhull** [comment]
Check adjusting the font sizing value in the json and see if that helps. I
adjusted mine to my taste as it was too big originally for my preference.

**Comment by riverar** [comment]
The templates I tried don't mess with the font size (e.g. isotope).

**Comment by sheldonhull** [comment]
I'd try plugging that in. Maybe the font and other settings in that theme
should have a font size set to avoid the resizing being too small. If you
try and it helps then perhaps the theme json could be updated and fix it
for others. I know font has a big impact for me.

**Comment by h404bi** [comment]
Resetting the fontFace back to Lucida Console or Raster Font should resolve this. Update to the latest version of concfg and use `concfg import basic-reset`.
