### ISSUE TITLE
Thank You!!!

### ISSUE THREAD

**Issue by ryanerwin** [lukesampson/concfg#36]
I don't usually make silly posts like this, but from the moment I moved from Mac OS X around 3 years ago until now, the strangeness of colors that don't match between different between Cmd, PowerShell, and eventually WSL has always been nauseating.

I just for the first time ran:

```
concfg clean
```

After launching PowerShell, it finally matches cmd and WSL!

Whatever ConHost based task, regardless of being launched from the Start Menu or from Start + Run, or from `Keypirinha` - they all finally look the same!!!

You fixed it!

**Comment by atomicnumber1** [comment]
Came here to create such issue. Honestly, Thank You!

**Comment by countzero** [comment]
Thank you! Finally a way to increase the legibililty of the Windows consoles.

To give something back: I automated the thing including the font installation. Take a look at: https://github.com/countzero/windows_console_style
