### ISSUE TITLE
Color Tool support

### ISSUE THREAD

**Issue by DarthSpock** [lukesampson/concfg#39]
Following along from https://github.com/Microsoft/console/issues/62, it appears there's some differences in behavior between concfg and the Color Tool. Could you assist making concfg compatible with Color Tool? I'd love to have centralized management with these 2 great tools that aim to achieve the same thing.

**Comment by lukesampson** [comment]
Thanks for bringing this to my attention, but I'm sorry to say I'm not actively developing concfg any more.

If these two tools do the same thing I would expect Color Tool to take over if it's actively developed and supported by Microsoft.

Do you think the most productive way forward would be to convert concfg's .json themes to Color Tool's .itemcolors?

**Comment by DarthSpock** [comment]
Well the Color Tool is open-source so you could of course commit to the repo for it which I have linked: https://github.com/Microsoft/Console/tree/master/tools/ColorTool.  This is what one of the Console/Color Tool contributors said:

> So, I had a crack at writing a simple json parser and that all works as you'd expect. But I realized after the fact that concfg does colour schemes slightly differently from our iterm/ini schemes in that it explicitly sets the screen text/background in the console properties, not just the values of the colour table. The end result is that some schemes (particularly light schemes where the background colour is set to a different index in the table) don't appear as you'd expect them to.

So the issue has to do with the indexes from what I gather. If all people want are the themes, what you propose would be sufficient. However, I think fixing the index issue would probably be a better expense of your time. I asked the contributor to work with you if you're willing to resolve the issue, though fully understanding you aren't actively developing this project anymore, and so is up to your prerogative.

**Comment by DarthSpock** [comment]
Never got a response back for this. So just pinging so it doesn't fall off the radar (unless that's intentional), in which case I can close the issue.

**Comment by h404bi** [comment]
ColorTool has supported to import concfg's json presets. This can be close I think.
