### ISSUE TITLE
concfg import solarized fails

### ISSUE THREAD

**Issue by voxelv** [lukesampson/concfg#51]
When I try importing solarized small, I get the following error. 

PS C:\redacted> concfg import solarized small
concfg: ERROR: couldn't load settings from solarized

**Comment by lukesampson** [comment]
Looks like there's some outdated documentation somewhere.

You need to choose the dark or light Solarized theme, e.g. `concfg import solarized-dark` should work.

You can list the available presets with `concfg presets`.

**Comment by voxelv** [comment]
Ah ok, yep. Looks like it works now. 

The "outdated documentation" is the video at https://scoop.sh/

**Comment by corbob** [comment]
It's also the readme that's outdated...

I've done up PR #53 to correct the ReadMe.
