### ISSUE TITLE
Always install the most recent version (update)

### ISSUE THREAD

**Issue by markfaine** [lukesampson/concfg#63]
I plan on trying to use ansible to install some scoop packages through WSL.  The idea though is that every time the playbook runs it should install the most recent version of the app.  This won't work though because it will just report that the app is already installed.  I have to do two operations:  Install, followed by an update.  It would be nice if there were a way to combine these steps into a single operation.

**Comment by h404bi** [comment]
Not sure what you mean, but you can always get the latest version of concfg from Scoop.
https://github.com/lukesampson/scoop/commits/master/bucket/concfg.json

**Comment by markfaine** [comment]
Imagine you want to install the most recent version on a computer but you don't know if it is already installed, and if it is installed, you don't know the version.  This means that in an automated scenario in order to ensure you had the latest version you'd have to do scoop install and then scoop update.  All I'm saying is that it would be nice if upgrade would also install if it's not installed or install could have a flag, something like --upgrade.  Either way, only one command would be required to ensure the latest version was installed.

**Comment by markfaine** [comment]
Not that I think about it this belongs more as a feature request to scoop.  Not sure why I submitted it here.
