### ISSUE TITLE
cmd-default and powershell-default don't reset the font anymore

### ISSUE THREAD

**Issue by Megasware128** [lukesampson/concfg#69]
I'm used to able to reset my entire terminal to default settings but the fonts and other stuff seem to stay same.

**Comment by h404bi** [comment]
`cmd-default` and `powershell-default` only cover ColorTable settings, all color-only presets does not  change non-color settings of your console now. Which preset did you use to override the non-color settings?

**Comment by Megasware128** [comment]
Not sure, believe I had a custom preset once. But just found out 'basic' does what I want

**Comment by h404bi** [comment]
Glad to here that, the `basic` preset is just a non-color preset, and it's just extracted from the old removed `windows-console-defaults` preset. Here is a preset for resetting font settings and I'll add it to the built-in presets soon with name `basic-reset.json`.

```json
{
    "font_face": "",
    "font_true_type": false,
    "font_size": "0x14",
    "font_weight": 0,
    "cursor_size": "small",
    "window_size": "80x25",
    "screen_buffer_size": "80x200",
    "command_history_length": 50,
    "num_history_buffers": 4,
    "quick_edit": false,
    "insert_mode": true,
    "fullscreen": false,
    "load_console_IME": true
}
```

**Comment by h404bi** [comment]
should be resolved and closed after commit https://github.com/lukesampson/concfg/commit/a38c23651458ea48e463f7402bf166c65855759f
