### ISSUE TITLE
Cannot reset colors to default windows scheme

### ISSUE THREAD

**Issue by dhdguysg** [lukesampson/concfg#7]
I have been using concfg for a while, But its starting to get on my nerve when it comes to programming, It sets all of my programs to the solarized color theme (even when i run concfg clean) so i need help doing it, I'd like to keep it on my PowerShell and Command Prompt though, Please help!

**Comment by dhdguysg** [comment]
EDIT: concfg import grayscale resets the console back to the original grayscale theme, Thanks! (closed)

**Comment by dhdguysg** [comment]
FIX: concfg import defaults, It even fixed what git did making the font no longer bitmap, Thanks for concfg! so useful!

**Comment by lukesampson** [comment]
Cool, glad you found that :smile:
