### ISSUE TITLE
Recent XDG_CONFIG_HOME refactor seems to cause an issue for fresh installs

### ISSUE THREAD

**Issue by joshgentry** [lukesampson/concfg#70]
I haven't had an opportunity to dig deeply, so I'm only seeing what is the most likely culprit, but the recent commit https://github.com/lukesampson/pshazz/commit/9bda1e39c0cd02c926f6d2495a4c4d26c8bba123 may have adjusted setting up a fresh install in a way that fails to create the config file if it does not exist (as the path does not exist).

This is the error I'm seeing:
```
Set-Content : Could not find a part of the path 'C:\Users\user\.config\pshazz\config.json'.
At C:\Users\user\scoop\apps\pshazz\current\lib\config.ps1:24 char:27
+     ConvertTo-Json $cfg | Set-Content $configFile -Encoding ASCII
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\user\.config\pshazz\config.json:String) [Set-Content], DirectoryNotFoundException
    + FullyQualifiedErrorId : GetContentWriterDirectoryNotFoundError,Microsoft.PowerShell.Commands.SetContentCommand
```

This error occurs immediately after:
```
scoop install --arch 64bit concfg
scoop install pshazz
concfg import gruvbox-dark-medium
pshazz use lambda
```

Note that running `pshazz init` does not correct the issue.

**Comment by h404bi** [comment]
Hello joshgentry, thanks for reporting the issue. The issue confirmed, but it's related to pshazz, could you reopen it in pshazz's [issue tracker](https://github.com/lukesampson/pshazz/issues)? Will fix it soon.

**Comment by joshgentry** [comment]
@h404bi ah you're right, my bad. Will re-open over in pshazz.
