### ISSUE TITLE
Export Error, when file is 'con', it failed

### ISSUE THREAD

**Issue by wenmin92** [lukesampson/concfg#73]
See below:

![image](https://user-images.githubusercontent.com/6901815/62417085-e58c8380-b679-11e9-90bb-3b39014caec3.png)

**Comment by h404bi** [comment]
https://www.helpndoc.com/documentation/html/Windowsreservedfilenames.html
Don't USE reserved names to create files.

**Comment by wenmin92** [comment]
Oh, That's interesting, TKS
